http:
    port: 8082
    shutdown_time: 5s
    read_time: 10s

    allowed_origins:
        - http://localhost:3000
        - http://localhost:58271


api:
    logs_storage:
        host: "localhost"
        port: 8081

auth:
    username: "admin"
    password: "admin"

## logger
logger:
    level: DEBUG
    to_file: true
    to_stderr: true
    fn: "logsViewer.log"
    max_size_mb: 100
    max_files: 10




    

